### ISSUE TITLE
Can't set shared property for rollingfile settings

### ISSUE THREAD

**Issue by Jajunk** [serilog/serilog-extensions-logging-file#11]
We seem to be able to configure all rollingfile settings except for file sharing. The code for some reason has a preprocessor directive to set it to true or false if SHARED is defined, but it is not and there is no way to set that via code (obviously). We should be able to set this property.

**Comment by nblumhardt** [comment]
Thanks for the note. Sharing wasn't originally supported for .NET Core, hence the `#if`. It has been for a while though, so I've just PR'd a change to enable it on all platforms.

Are you able to check out package version 1.1.0-dev-00014 to make sure this works as expected for your target? Should be a safe/low-impact change to push through to master.

**Comment by Jajunk** [comment]
@nblumhardt Looks to be working fine.

**Comment by nblumhardt** [comment]
Thanks @Jajunk

**Comment by alexiordan** [comment]
Not working in 3.3.0 version.
