### ISSUE TITLE
Output categories in log file

### ISSUE THREAD

**Issue by tomasaschan** [serilog/serilog-extensions-logging-file#14]
The current log string format doesn't output the category of the entry - at least not by default, but maybe I'm overlooking a configuration option somewhere?

If output of log item category is not supported today, are there any plans for it in the future?

**Comment by nblumhardt** [comment]
Hi Tomas, thanks for getting in touch.

This isn't supported as things stand today; the current plan is to keep the API surface of this library fairly minimal, and fall back to the full Serilog API for options that aren't in the default set.

As a responder on SO suggested, you could also consider switching to JSON events instead (and use something like [clef-tool](https://nblumhardt.com/2017/07/clef-tool/) to pretty-print them :-)).

Thoughts?

**Comment by tlycken** [comment]
@nblumhardt Thanks for getting back! I'm sorry I've been a bit slow - vacation time :) I'll be back at work in a week from now, so until then I'll only check in here sporadically...

By "the full Serilog API", I assume you're referring to https://github.com/serilog/serilog-extensions-logging? I'll give that a try once I get back to work. Thanks!
