### ISSUE TITLE
Logging stopped after upgrading to aspnetcore 2.0

### ISSUE THREAD

**Issue by mrahhal** [serilog/serilog-extensions-logging-file#19]
We have a project that we upgraded to aspnetcore 2.0. We have 2 logging providers, a console and a serilog file. After the upgrade (we didn't change anything related to logging at all), logging to a file stopped completely, the console logging is still working.

I updated this package to 2.0 preview, but the same still happened.

The config code is very simple:
```
loggerFactory.AddConsole(Configuration.GetSection("Logging"));
loggerFactory.AddFile(Configuration.GetSection("Serilog"));
```

**Comment by nblumhardt** [comment]
Hi @mrahhal - there were some changes to the implementation of logging in ASP.NET Core 2.0 that caused us to rethink our approach. The recommended package is now https://github.com/serilog/serilog-aspnetcore with some info at https://nblumhardt.com/2017/08/use-serilog/.

Does this help? Thanks!

**Comment by mrahhal** [comment]
Oh. I see, I saw serilog-aspnetcore but thought the approach of this repo was easier for just a simple log file. I'll read the article and try serilog-aspnetcore. Thanks!

**Comment by mrahhal** [comment]
One more thing, maybe something should be added to the README? I really searched a lot in the issues and the README but found absolutely nothing about it.

Also, does that mean this library will stay as legacy for aspnetcore 1.0 only, and moving forward we should be using serilog-aspnetcore?

**Comment by nblumhardt** [comment]
Sorry @mrahhal - I misread the repo title and mistook this one for `serilog-extensions-logging`, which is effectively being replaced by `serilog-aspnetcore` for most purposes in 2.0.

This package should continue to work - I'll have a look at what's going on in the 2.0-dev version.

(It may also be fairly quick and easy just to move across to _Serilog.AspNetCore_ and _Serilog.Sinks.RollingFile_ if you need to move quick :-))

**Comment by mrahhal** [comment]
Oh OK. That explains things because I was starting to get confused 😅 

I guess I don't have a chance, I'll try out serilong-aspnetcore with a rolling file sink. And maybe I can come back to this later (I really tried, but I wasn't able to figure what the problem was, the configuration was being read correctly, maybe I'll try creating a repro)

**Comment by nblumhardt** [comment]
Thanks! Good luck 👍

**Comment by mrahhal** [comment]
So I looked into Serilog.AspNetCore, but it turned out to be much more than what I needed, at least for now. So I went back to try again, I transformed the startup/program code to match better what is being recommended in 2.0. And it started working again.

Not entirely sure, but I had the (aspnet) configuration building in startup, I moved it inside `ConfigureAppConfiguration` in Program.cs. Might not be the particular problem, but pretty sure it was caused by the way I was configuring things the old way (1.0).

**Comment by nblumhardt** [comment]
Great! Glad to hear you got it working, thanks for sharing the results.

**Comment by justintoth** [comment]
I'm running into the same issue where Serilog logging just stops working randomly in some of our applications, without giving any failures either in the form of exceptions thrown or in the debug logging. I'm concerned that the solution is to switch to this aspnetcore serilog package for two reasons:

1. If we're using logging across our system, both in aspnet core apps, and other apps (windows services, console apps, etc...) then we need to maintain two sets of code to handle logging both ways.
2. The aspnet core serilog package gets rid of adding logging configurations via loggingfactory.add and instead wants you to set log.logger = the configuration. This is all nice and good if you only have one logging sink, but doesn't address if you have multiple sinks (e.g. console and sql server.)

**Comment by nblumhardt** [comment]
(See also: https://github.com/serilog/serilog-aspnetcore/issues/35)
