### ISSUE TITLE
Ability to configure the message template

### ISSUE THREAD

**Issue by mrahhal** [serilog/serilog-extensions-logging-file#20]
It would be super nice if we were able to configure the message template instead of it being hard coded [here](https://github.com/serilog/serilog-extensions-logging-file/blob/dev/src/Serilog.Extensions.Logging.File/Microsoft/Extensions/Logging/FileLoggerExtensions.cs#L132).

I know that this library is opinionated and that the full serilog is recommended for more complex use cases, but this one is very easy to do with great benefits. I don't see myself ever needing the full serilog, but changing the message template would be very nice to have.

**Comment by mrahhal** [comment]
Commenting, just to note that after a whole year, this is one of our blockers for using this awesome simple package instead of rolling our own :)

**Comment by merbla** [comment]
@mrahhal have you had a chance at all to put a PR together at all for the concept you are proposing?

**Comment by mrahhal** [comment]
Not really, haven't thought of it because I already went through the trouble of setting serilog. If I get some free time soon I'll do it.

**Comment by rloomans** [comment]
@mrahhal does #30 look like something like what you wanted?

**Comment by mrahhal** [comment]
@rloomans exactly what I want. Thanks!

**Comment by mrahhal** [comment]
Anyone can please take a look at #30 or #8? The functionality is ready there and lots of people really need this configuration option. It's been a really really long while.

**Comment by mrahhal** [comment]
Ah.. I checked the last commit here, is this project still being maintained at all? I'm starting to think I'll have to fork and release my own package with this included! @rloomans thoughts?
