### ISSUE TITLE
Question about Request Id?

### ISSUE THREAD

**Issue by linianhui** [serilog/serilog-extensions-logging-file#21]
https://github.com/serilog/serilog-extensions-logging-file/blob/17ea51959ee61fe4cc8b4f035482add4d99b0062/src/Serilog.Extensions.Logging.File/Microsoft/Extensions/Logging/FileLoggerExtensions.cs#L132

I don't understand how serlog gets the value of requestid,How does it work?

**Comment by nblumhardt** [comment]
Hi,

This is pushed onto the logging context by ASP.NET via `BeginScope()` within the HTTP request processing pipeline.

HTH,
Nick

**Comment by linianhui** [comment]
Thank you.I found it https://github.com/serilog/serilog-extensions-logging/blob/dev/src/Serilog.Extensions.Logging/Extensions/Logging/SerilogLogger.cs#L45-L48
