### ISSUE TITLE
Request id doesn't seem to be correct

### ISSUE THREAD

**Issue by BorisMisic** [serilog/serilog-extensions-logging-file#26]
My ASP.NET Core web API uses Serilog.Extensions.Logging.File version 1.1.0 and here is the sample of a log file generated from it 
[myLog-20180703.log](https://github.com/serilog/serilog-extensions-logging-file/files/2163577/myLog-20180703.log)
I had "The operation timed out" exception recorded under Request id = 0HLF0SCB4K08A. I know that web request to my web API makes only one call to https://_ _ _/products/(...)?_ _ _ URL. However, I see call to this URL in line 1, 4, 9 and 16. What does a code after : means? Is it a part of Request id? Please explain.

**Comment by TiraelSedai** [comment]
It is a part of Request ID indeed
