### ISSUE TITLE
DNC 3.1 on Unbuntu Missing Method Exception

### ISSUE THREAD

**Issue by NVentimiglia** [serilog/serilog-extensions-logging-file#36]
- Issue is not seen on windows
- Issue is only seen on my server (Linux Unbuntu running DNC 3.1)
- Removing Serilog fixes the issue
- Stack trace below

> root:~/SimpleOffice# dotnet SimpleOffice.dll
> Application startup exception: System.MissingMethodException: Method not found: 'Microsoft.Extensions.Logging.ILoggerFactory Microsoft.Extensions.Logging.FileLoggerExtensions.AddFile(Microsoft.Extensions.Logging.ILoggerFactory, System.String, Microsoft.Extensions.Logging.LogLevel, System.Collections.Generic.IDictionary`2<System.String,Microsoft.Extensions.Logging.LogLevel>, Boolean, System.Nullable`1<Int64>, System.Nullable`1<Int32>)'.
>    at SimpleOffice.Startup.ConfigureLogger(ILoggerFactory loggerFactory, IHttpContextAccessor http)
>    at SimpleOffice.Startup.Configure(IApplicationBuilder app, IServiceScopeFactory factory, IWebHostEnvironment env, IHttpContextAccessor http, ILoggerFactory loggerFactory) in D:\Projects\SimpleSys\SimpleOffice\SimpleOffice\SimpleOffice\Startup.cs:line 138
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
>    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
>    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
>    at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
>    at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
>    at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
> crit: Microsoft.AspNetCore.Hosting.WebHost[6]
>       Application startup exception
> System.MissingMethodException: Method not found: 'Microsoft.Extensions.Logging.ILoggerFactory Microsoft.Extensions.Logging.FileLoggerExtensions.AddFile(Microsoft.Extensions.Logging.ILoggerFactory, System.String, Microsoft.Extensions.Logging.LogLevel, System.Collections.Generic.IDictionary`2<System.String,Microsoft.Extensions.Logging.LogLevel>, Boolean, System.Nullable`1<Int64>, System.Nullable`1<Int32>)'.
>    at SimpleOffice.Startup.ConfigureLogger(ILoggerFactory loggerFactory, IHttpContextAccessor http)
>    at SimpleOffice.Startup.Configure(IApplicationBuilder app, IServiceScopeFactory factory, IWebHostEnvironment env, IHttpContextAccessor http, ILoggerFactory loggerFactory) in D:\Projects\SimpleSys\SimpleOffice\SimpleOffice\SimpleOffice\Startup.cs:line 138
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
>    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
>    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
>    at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
>    at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
>    at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
> Unhandled exception. System.MissingMethodException: Method not found: 'Microsoft.Extensions.Logging.ILoggerFactory Microsoft.Extensions.Logging.FileLoggerExtensions.AddFile(Microsoft.Extensions.Logging.ILoggerFactory, System.String, Microsoft.Extensions.Logging.LogLevel, System.Collections.Generic.IDictionary`2<System.String,Microsoft.Extensions.Logging.LogLevel>, Boolean, System.Nullable`1<Int64>, System.Nullable`1<Int32>)'.
>    at SimpleOffice.Startup.ConfigureLogger(ILoggerFactory loggerFactory, IHttpContextAccessor http)
>    at SimpleOffice.Startup.Configure(IApplicationBuilder app, IServiceScopeFactory factory, IWebHostEnvironment env, IHttpContextAccessor http, ILoggerFactory loggerFactory) in D:\Projects\SimpleSys\SimpleOffice\SimpleOffice\SimpleOffice\Startup.cs:line 138
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
>    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
>    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
>    at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
>    at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
>    at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
>    at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
>    at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
>    at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
>    at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
>    at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
>    at SimpleOffice.Program.Main(String[] args) in D:\Projects\SimpleSys\SimpleOffice\SimpleOffice\SimpleOffice\Program.cs:line 30

**Comment by NVentimiglia** [comment]
I also tried manually adding the Microsoft Logging Configuration and Configuration Abstracts packages. It gave me warnings and did not work.

**Comment by nblumhardt** [comment]
Thanks for the report. I just hit the button - very, very belatedly - on the v2.0.0 of this package which targets some newer dependencies. Any chance that fixes the issue for you?

**Comment by nblumhardt** [comment]
(Sorry, accidental "close" button press 😅 )

**Comment by NVentimiglia** [comment]
This worked!
