### ISSUE TITLE
ASP Net Core Logs written even if "Microsoft.*"="None" (appsettings.json)

### ISSUE THREAD

**Issue by sylvainonweb** [serilog/serilog-extensions-logging-file#39]
Hi,

I downloaded your repository and launched the example project and saw a lot of noisy logs were generated by the aspnetcore itself.
I tried to set the Microsoft entry of the appsettings.json to None but it didn't change anything.
Must I use your UseSerilogRequestLogging even if I just don't want this kind of logs?

```
{
  "Logging": {
    "PathFormat": "Logs/log-{Date}.txt",
    "OutputTemplate": "{Timestamp:o} {RequestId,13} [{Level:u3}] {Message} ({EventId:x8}) {Properties:j}{NewLine}{Exception}",
    "IncludeScopes": true,
    "LogLevel": {
      "Default": "Warning",
      "Microsoft.*": "None"
    }
  }
}
```

**Comment by nblumhardt** [comment]
Hi! The level is called `Off`, not `None` - HTH!

**Comment by nblumhardt** [comment]
Sorry, my mistake - `None` is correct. It's the trailing `.*` in your rule that is incorrect. Should be:

```
      "Microsoft": "None"
```

**Comment by sylvainonweb** [comment]
Hi, 

I triedusing "Microsoft":"None" and it doesn't change anything.
See attachment

[log-20200326.txt](https://github.com/serilog/serilog-extensions-logging-file/files/4385301/log-20200326.txt)

**Comment by nblumhardt** [comment]
Ah, sorry, it was a busy morning. You also need to set the "Microsoft" level override through Serilog configuration, the "Logging" section is for the default logger. Check out _Serilog.Settings.Configuration_, or `MinimumLevel.Override("Microsoft", LogEventLevel.Fatal)` in your C# Serilog config.

**Comment by sylvainonweb** [comment]
But if I do it on my own project, it's OK 👍

**Comment by nblumhardt** [comment]
Great :+1:
