### ISSUE TITLE
Logger is not disposed along with ServiceProvider

### ISSUE THREAD

**Issue by aleksey-s902** [serilog/serilog-extensions-logging-file#47]
Repro: https://github.com/aleksey-s902/SerilogProviderNotDisposedRepro

```
        static void Main(string[] args)
        {
            var serviceProvider = new ServiceCollection()
                .AddLogging(builder =>
                {
                    builder.AddFile("test.log");
                })
                .BuildServiceProvider();

            var logger = serviceProvider.GetService<ILogger<Program>>();
            logger.LogError("test");
            
            serviceProvider.Dispose();
            // Thread.Sleep(5000);
        }
```
Problem with this code: the log file isn't written. There is obviously a race condition because if I uncomment `Thread.Sleep`, the log file appears correctly. My understanding of what happening there is:
- `AddFile` adds an async file writer which runs in a background thread
- Application shuts down before the background thread has a chance to write the log file
- Normally, this is prevented by disposing logger before shutdown. I would expect that in this case ServiceProvider would dispose the logger. However, that isn't happening.

As to why it isn't happening: I suppose that's caused by the same reason as https://github.com/aspnet/Hosting/issues/1466. `AddSerilog` register an instance of `SerilogLoggerProvider`, and ServiceProvider won't dispose anything added as an instance.

Workaround: dispose the logger provider manually:
```
serviceProvider.GetService<ILoggerProvider>().Dispose();
```

**Comment by nblumhardt** [comment]
Thanks! I think this is very likely due to a bug in the old version of Serilog.Sinks.Async 1.1.0 that this package installs. If you add a manual dependency on Serilog.Sinks.Async 1.4.0, and the problem is fixed, we should update this package to pull in the newer one.

(Serilog.Extensions.Logging has also had some disposal-related bugs over the years, so trying an update of that one could be worthwhile, too.)

HTH!

**Comment by xv-aleksey-s** [comment]
@nblumhardt updating Serlilog.Sinks.Async 1.4.0 didn't help, but after I updated Serilog.Extensions.Logging to 3.1.0 it started worked as expected, thanks!

**Comment by aleksey-s902** [comment]
@nblumhardt updating Serlilog.Sinks.Async 1.4.0 didn't help, but after I updated Serilog.Extensions.Logging to 3.1.0 it started working as expected, thanks!

**Comment by nblumhardt** [comment]
Great! Thanks for the info. Time for a dependency update, here 👍

**Comment by mmarinchenko** [comment]
PR #51 linked.
