### ISSUE TITLE
Current User support

### ISSUE THREAD

**Issue by axelheer** [serilog/serilog-extensions-logging-file#6]
I'm logging the current user once per request. Thus, I'm able to find a single request of a specific user, but it would be nice to just filter log entries by the current user.

It already seems to be possible using some kind of [middleware ceremony](http://stackoverflow.com/questions/39896465/add-user-to-the-log-context-when-using-serilog-and-asp-net-core), but having a "one line" solution here would be really nice.

**Comment by nblumhardt** [comment]
Thanks for the note. The role of this library is really just to be minimal glue between Serilog and Microsoft.Extensions.Logging - there might be a better place to house the logging middleware but I don't think there's currently an assembly under the Serilog project that would be a good home for this.

Once you have some logging middleware in there, you can do quite a bit more though; check out: http://blog.getseq.net/smart-logging-middleware-for-asp-net-core/ - adding the extra event enrichment for the current user into the example `SerilogMiddleware` class would be less effort/ceremony if you're already going the extra mile to customize logging.

What do you think?

**Comment by axelheer** [comment]
Maybe I'll just go with a custom middleware, yeah. Thanks for the link!

Another idea (I'm new to Serilog...): make the message text configurable. Then one could use whatever "enrichment" possible. (?)

**Comment by nblumhardt** [comment]
Ah, sorry; I'd misread this as being in the serilog-extensions-logging repository, not the -file one. My mistake!

At least at present, I'm keen to keep this library configuration-free as much as possible. There are so many ways to tweak it, we'll just end up replicating the Serilog API.

I think in this case, if you want the username in the log file, it'd be best to configure Serilog directly and avoid this library. There are a couple of [notes on how to do this](https://github.com/serilog/serilog-extensions-logging-file#using-the-full-serilog-api), but the docs would benefit from some expansion if you hit any challenges. Cheers!
